name: zillow
description: Client for working with Zillow Web Services
version: 0.0.1
homepage: https://github.com/madisona/dart-zillow
author: Aaron Madison <aaron.l.madison@gmail.com>

environment:
  sdk: '>=2.0.0-dev.48.0 <2.0.0'

dependencies:
  xml2json: "^2.0.13"

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.8.0
  json_serializable: ^0.5.0
