name: zillow
description: Client for working with Zillow Web Services
version: 0.0.1
homepage: https://github.com/madisona/dart-zillow
author: Aaron Madison <aaron.l.madison@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  xml: "^3.0.0"

dev_dependencies:
  test: ^0.12.0
